[package]
name = "Audio_visualiser"
version = "0.1.0"
edition = "2024"

[dependencies]
hound = "3.4.0"
pyo3 = { version = "0.18", features = ["extension-module"] }

[lib]
name = "audio_processor"
crate-type = ["cdylib"]

[features]
python_bindings = []